---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: atemi-service-builder
  namespace: jenkins
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:alpine
  - name: docker-helm
    image: ecerqueira/docker-helm
    volumeMounts:
    - name: docker-sock-volume
      mountPath: /var/run/docker.sock
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
      type: File